import { createGame, playCard, legalCards } from './game.js';
import { CAMPAIGNS, missionFor } from './missions.js';
import { chooseBotCard } from './bot.js';
import { Multiplayer } from './multiplayer.js';

const app=document.querySelector('#app');
let campaign='orbital', missionNo=1, playerCount=4, game=null, multiplayer=null, lobbyState=null;
let bots=new Set([1,2,3]);

function el(tag,attrs={},children=[]){const n=document.createElement(tag);for(const[k,v]of Object.entries(attrs)){if(v==null)continue;if(k==='class')n.className=v;else if(k==='html')n.innerHTML=v;else if(k.startsWith('on'))n.addEventListener(k.slice(2).toLowerCase(),v);else if(k==='selected')n.selected=!!v;else n.setAttribute(k,v)};for(const c of [].concat(children))n.append(c?.nodeType?c:document.createTextNode(c??''));return n;}
function localSeat(){return multiplayer?.role==='guest'?multiplayer.localSeat:0;}
function execute(seat,action,payload){if(action!=='play-card')return false;const result=playCard(game,seat,payload.cardId);if(!result.ok)return false;renderGame();if(multiplayer?.role==='host')multiplayer.sync();setTimeout(runBots,300);return true;}

function campaignScreen(){app.innerHTML='';const cards=Object.values(CAMPAIGNS).map(c=>el('button',{class:`campaign-card ${c.id}`,onclick:()=>{campaign=c.id;missionNo=1;setupScreen();}},[el('span',{class:'eyebrow'},c.subtitle),el('strong',{},c.name),el('p',{},c.flavor),el('small',{},`${c.missionCount} mission templates`)]));app.append(el('main',{class:'menu-shell'},[el('header',{class:'brand'},[el('span',{class:'eyebrow'},'COOPERATIVE TRICK-TAKING'),el('h1',{},'OPENCREW'),el('p',{},'Choose an expedition. Play solo with bots or create a private crew.')]),el('section',{class:'campaign-grid'},cards)]));}

function setupScreen(){const c=CAMPAIGNS[campaign];app.innerHTML='';app.append(el('main',{class:`setup ${campaign}`},[el('button',{class:'back',onclick:campaignScreen},'← Expeditions'),el('div',{class:'setup-card'},[el('span',{class:'eyebrow'},c.subtitle),el('h1',{},c.name),el('p',{},c.flavor),el('label',{},['Mission ',el('input',{type:'number',min:'1',max:String(c.missionCount),value:String(missionNo),onchange:e=>missionNo=Math.max(1,Math.min(c.missionCount,+e.target.value||1))})]),el('label',{},['Crew size ',el('select',{onchange:e=>{playerCount=+e.target.value;bots=new Set(Array.from({length:playerCount-1},(_,i)=>i+1))}},[2,3,4,5].map(n=>el('option',{value:n,selected:n===playerCount},String(n))))]),el('button',{class:'primary',onclick:startLocal},'Start with bots'),el('button',{class:'secondary',onclick:multiplayerScreen},'Private multiplayer')]) ]));}

function startLocal(){multiplayer=null;game=createGame({playerCount,mode:campaign,mission:missionFor(campaign,missionNo,playerCount)});renderGame();setTimeout(runBots,300);}
function initMP(){multiplayer=new Multiplayer({onState:s=>{game=s;campaign=s.mode;renderGame()},onLobby:s=>{lobbyState=s;renderLobby()},onError:e=>console.warn(e)});}

function multiplayerScreen(){initMP();lobbyState=null;app.innerHTML='';const name=el('input',{placeholder:'Your name',value:localStorage.getItem('opencrew.name')||'Player'});const code=el('input',{placeholder:'ROOM CODE',maxlength:'6'});const signal=el('input',{placeholder:'Signaling URL',value:localStorage.getItem('opencrew.signal')||'http://localhost:8787'});app.append(el('main',{class:`setup ${campaign}`},[el('button',{class:'back',onclick:setupScreen},'← Back'),el('div',{class:'setup-card'},[el('span',{class:'eyebrow'},'PRIVATE WEBRTC CREW'),el('h1',{},'Multiplayer'),el('p',{},'One player hosts the authoritative simulation. Guests send only actions; hidden hands stay hidden.'),el('label',{},['Name ',name]),el('label',{},['Signal ',signal]),el('button',{class:'primary',onclick:async()=>{localStorage.setItem('opencrew.name',name.value);localStorage.setItem('opencrew.signal',signal.value);multiplayer.signalUrl=signal.value;await multiplayer.createRoom(name.value||'Host');}},'Create room'),el('label',{},['Code ',code]),el('button',{class:'secondary',onclick:async()=>{localStorage.setItem('opencrew.name',name.value);localStorage.setItem('opencrew.signal',signal.value);multiplayer.signalUrl=signal.value;await multiplayer.joinRoom(code.value,name.value||'Guest');}},'Join room')]) ]));}

function renderLobby(){if(!lobbyState)return;const s=lobbyState;app.innerHTML='';const seats=[];for(let i=0;i<playerCount;i++){const human=i===0?s.names[0]:s.names[i];const bot=s.botSeats[i];seats.push(el('div',{class:'task'},[el('span',{},human?'●':bot?'◆':'○'),el('p',{},human|| (bot?`Bot · ${bot}`:`Seat ${i+1} empty`)),s.role==='host'&&i>0&&!human?el('button',{class:'ghost',onclick:()=>multiplayer.setBot(i,bot?null:'hard')},bot?'Remove bot':'Add bot'):'' ]));}const startReady=s.role==='host';app.append(el('main',{class:`setup ${campaign}`},[el('div',{class:'setup-card'},[el('span',{class:'eyebrow'},s.role==='host'?'HOST LOBBY':'GUEST LOBBY'),el('h1',{},s.room||'Connecting…'),el('p',{},`${s.connected||0} peer connection(s)`),...seats,s.role==='host'?el('button',{class:'primary',disabled:startReady?null:'disabled',onclick:startMultiplayerGame},'Start mission'):el('p',{},'Waiting for host to start…')]) ]));}

function startMultiplayerGame(){bots=new Set(Object.keys(multiplayer.botSeats).map(Number));game=createGame({playerCount,mode:campaign,mission:missionFor(campaign,missionNo,playerCount)});multiplayer.attachGame(game,execute);multiplayer.sync();renderGame();setTimeout(runBots,300);}
function runBots(){if(!game||game.status!=='playing'||!bots.has(game.currentPlayer))return;if(multiplayer?.role==='guest')return;const seat=game.currentPlayer;const card=chooseBotCard(game,seat,'hard');if(card){playCard(game,seat,card.id);renderGame();if(multiplayer?.role==='host')multiplayer.sync();setTimeout(runBots,340)}}
function cardNode(card,playable=false){if(card.hidden)return el('div',{class:'card back-card'},'');return el('button',{class:`card ${card.suit} ${playable?'playable':''}`,onclick:playable?()=>{if(multiplayer)multiplayer.action('play-card',{cardId:card.id});else execute(0,'play-card',{cardId:card.id})}:()=>{}},[el('b',{},String(card.value)),el('span',{},card.suit==='rocket'?'▲':card.suit[0].toUpperCase())]);}

function renderGame(){if(!game)return;app.innerHTML='';const mission=game.mission;const me=localSeat();const myHand=game.hands[me]||[];const legalIds=new Set(game.currentPlayer===me?legalCards(myHand,game.trick).filter(c=>!c.hidden).map(c=>c.id):[]);const rivals=[];for(let s=0;s<game.playerCount;s++){if(s===me)continue;rivals.push(el('div',{class:`seat seat-${(s%4)+1}`},[el('strong',{},multiplayer?.names?.[s]||`CREW ${s+1}`),el('span',{},`${game.hands[s].length} cards`)]));}const trick=game.trick.map(x=>el('div',{class:'trick-card'},[cardNode(x.card),el('small',{},`Crew ${x.seat+1}`)]));const tasks=mission.tasks.map((t,i)=>el('div',{class:`task ${game.taskState[i]?.complete?'done':''} ${game.taskState[i]?.failed?'failed':''}`},[el('span',{},game.taskState[i]?.complete?'✓':game.taskState[i]?.failed?'×':'○'),el('p',{},t.label)]));app.append(el('main',{class:`game ${campaign}`},[el('header',{class:'hud'},[el('div',{},[el('span',{class:'eyebrow'},CAMPAIGNS[campaign].subtitle),el('strong',{},CAMPAIGNS[campaign].name)]),el('div',{class:'hud-stat'},`Mission ${missionNo}`),el('div',{class:'hud-stat'},`Trick ${game.trickNo}`),el('button',{class:'ghost',onclick:setupScreen},'Menu')]),el('aside',{class:'mission-rail'},[el('span',{class:'eyebrow'},mission.title),el('h2',{},'Objectives'),...tasks]),el('section',{class:'table'},[...rivals,el('div',{class:'table-mark'},campaign==='orbital'?'ORBITAL RELAY':campaign==='abyss'?'SONAR ARRAY':'STORM GRID'),el('div',{class:'trick'},trick),el('div',{class:'status'},game.status==='playing'?`Crew ${game.currentPlayer+1} to play`:game.status==='won'?'MISSION COMPLETE':'MISSION FAILED'),el('div',{class:'hand'},myHand.map(c=>cardNode(c,game.currentPlayer===me&&legalIds.has(c.id))))]) ]));}

campaignScreen();
